trigger:
  branches: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'acrmlretail'

stages:
- stage: Build
  jobs:
  - job: BuildImages
    steps:
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/train:$(Build.BuildId) -f aml/train.Dockerfile .
        docker build -t $(ACR_NAME).azurecr.io/infer:$(Build.BuildId) -f aml/infer.Dockerfile .
      displayName: Build Docker images
