apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - addons/metrics-server.yaml
  - addons/cluster-autoscaler.yaml
  - addons/aws-load-balancer-controller.yaml
  - addons/external-dns.yaml
  - addons/secrets-store-csi/providerclass.yaml
  - pod-security-standards.yaml
  - rbac/read-only-role.yaml
  - pdb/server-pdb.yaml
  - ingress/alb-ingress.yaml
