apiVersion: v1
kind: Service
metadata:
  name: retail-forecast-svc
  namespace: mlops
  labels:
    app: retail-forecast
spec:
  selector:
    app: retail-forecast
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer
