apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ME_IRSA_CLUSTER_AUTOSCALER_ARN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: cluster-autoscaler }
rules:
  - apiGroups: [""]
    resources: ["events","endpoints"]
    verbs: ["create","patch"]
  - apiGroups: [""]
    resources: ["pods","services","replicationcontrollers","persistentvolumeclaims","nodes"]
    verbs: ["list","watch"]
  - apiGroups: ["extensions","apps"]
    resources: ["replicasets","deployments","statefulsets","daemonsets"]
    verbs: ["list","watch"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalers"]
    verbs: ["list","watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses","csinodes"]
    verbs: ["list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch","delete","get","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: cluster-autoscaler }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: cluster-autoscaler
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels: { app: cluster-autoscaler }
spec:
  replicas: 1
  selector:
    matchLabels: { app: cluster-autoscaler }
  template:
    metadata:
      labels: { app: cluster-autoscaler }
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - name: cluster-autoscaler
          image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.30.0
          command:
            - ./cluster-autoscaler
            - --cloud-provider=aws
            - --namespace=kube-system
            - --cluster-name=REPLACE_ME_EKS_CLUSTER_NAME
            - --balance-similar-node-groups=true
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --stderrthreshold=info
            - --v=4
          resources:
            requests: { cpu: 100m, memory: 300Mi }
            limits:   { cpu: 500m, memory: 600Mi }
