apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_ME_IRSA_EXTERNAL_DNS_ARN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  selector:
    matchLabels: { app: external-dns }
  template:
    metadata:
      labels: { app: external-dns }
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.14.0
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=REPLACE_ME_DOMAIN # e.g., dev.example.com
            - --provider=aws
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=REPLACE_ME_EKS_CLUSTER_NAME
